### ISSUE TITLE
Cannot locate delete link

### ISSUE THREAD

**Issue by jmayermsi** [LafColITS/moodle-tool_deletecourses#12]
After installing the plugin I am unable to find the link even after following the instructions listed here. Is there an alternative method to delete using your module?

**Comment by andyzito** [comment]
I've got a screenshot here of where the link should be located. This is on a category page, URL like `<mymoodle>/course/index.php?categoryid=<categoryid>`. You can get to a category page on your own site by manually entering this URL, or by following the main course navigation.

(screenshot blurred because it's from our internal Moodle)

![screenshot-moodle lafayette edu-2019 09 20-09_39_23](https://user-images.githubusercontent.com/14895702/65331689-410fc380-db8b-11e9-9b58-10d2f4b36851.png)

Please check for the link here, and if you still cannot see it, we can troubleshoot further.

**Comment by jmayermsi** [comment]
Thanks for posting, unfortunately, my screen doesn't display like this. I think the theme is causing the issue. Even when I use the URL schema you posted there is no method to do this.  Initially, I assumed you could access from the Manage Courses section in the admin but it's not listed there either.

**Comment by andyzito** [comment]
Hm, ok. Would it be possible for you to post or message me a screenshot of what you _are_ seeing?

**Comment by jmayermsi** [comment]
![course-delete2](https://user-images.githubusercontent.com/40437683/65335243-0cebd100-db92-11e9-9607-034ff110310f.jpg)

**Comment by jmayermsi** [comment]
Clicking the gear doesn't show your link

**Comment by andyzito** [comment]
Your screenshot includes gear icons for individual courses. You need the gear icon for the whole category rather than one individual course. It's difficult for me to direct you there without knowing your theme -- could you add a screenshot of the whole page?

**Comment by jmayermsi** [comment]
That's actually the point I was trying to make, this theme (remui)  doesn't list the categories, only the courses. The only way I can see the categories is inside the manage categories and courses section of the admin.

**Comment by andyzito** [comment]
Hmmm. I see. It's unfortunate that RemUI has chosen to hide the category navigation -- I would be inclined to report that to them as a bug/degradation, since it's a major piece of navigation that they're hiding from the user.

Obviously that doesn't help you in the short term, though. For a workaround, I think you should be fine just manually going to the URL for the deletion page: `<mymoodle>/admin/tool/deletecourses/delete.php?category=<categoryid>`

Please let me know if that works for you :)

**Comment by jmayermsi** [comment]
Perfect, thank you for that link, that will work.  Thanks for your help, just need to see if the cron job removes the courses

**Comment by andyzito** [comment]
Glad I could help.

**Comment by jmayermsi** [comment]
After running a delete of a category I got this error: 


Exception - Argument 1 passed to course_in_list::__construct() must be an instance of stdClass, null given, called in [dirroot]/lib/coursecatlib.php on line 1559

I don't see any courses in the category but when I view the category this error displays

**Comment by andyzito** [comment]
What version of Moodle are you using?

**Comment by jmayermsi** [comment]
3.41

**Comment by jmayermsi** [comment]
It may be working, the classes periodically show in the category. I can see some have been deleted. WHen I refresh the category the error message is intermittent with the list of classes.

**Comment by jmayermsi** [comment]
Courses look they are deleted now, but when they are in the process of being deleted the categeory displays that error when viewing the category

**Comment by mackensen** [comment]
@jmayermsi It sounds like you're encountering the caching issue described in #6.

**Comment by jmayermsi** [comment]
Yes this  is the issue, eventually, the errors are resolved.
